### ISSUE TITLE
Nothing's happening

### ISSUE THREAD

**Issue by GranVermo** [Lyall/PoPTLCFix#1]
Hi! Installed the mod according to the instructions. After entering the game - nothing happens.
I'm playing in steam.

**Comment by Lyall** [comment]
Can you post the the log file from `Prince of Persia The Lost Crown\BepInEx\LogOutput.log`?

**Comment by GranVermo** [comment]
> Can you post the the log file from `Prince of Persia The Lost Crown\BepInEx\LogOutput.log`?

Oh, I was wondering why I couldn't find his logs. They're not here. :(

![image](https://github.com/user-attachments/assets/65089cc2-8f79-42d2-ac78-286a022f7df2)

**Comment by Lyall** [comment]
Looks like I forgot to add the doorstop_config.ini fix that you need for this game. I've re-uploaded v0.8.2 with the updated file so can you try download it again and installing it? It should fix the launch issue.

**Comment by GranVermo** [comment]
> Looks like I forgot to add the doorstop_config.ini fix that you need for this game. I've re-uploaded v0.8.2 with the updated file so can you try download it again and installing it? It should fix the launch issue.

Yeah, it worked! Thank you!
