### ISSUE TITLE
The map is displayed incorrectly (fog)

### ISSUE THREAD

**Issue by GranVermo** [Lyall/PoPTLCFix#2]
Hi, it's me again :D

Problem: the map is covered by some fog and it's almost impossible to use. Attached a video. I saw in the description that there is a problem with icons, I hope this is not the same.

https://github.com/user-attachments/assets/e4adf0c1-bee3-4487-97d5-6e66d7d6a5db

**Comment by Lyall** [comment]
Nice catch, looks like I broke it with a past commit. Can you try this build? Just extract it in to the game directory and you'll be prompted overwrite the plugin dll.

[PoPTLCFix_v0.8.3.zip](https://github.com/user-attachments/files/16691915/PoPTLCFix_v0.8.3.zip)

**Comment by GranVermo** [comment]
Yes, everything is working. Many thanks again for your prompt help! <3
