### ISSUE TITLE
This is not an issue...

### ISSUE THREAD

**Issue by code-XmR** [Lyall/PoPTLCFix#3]
but I really don't know where to ask, is there any chance that you could consider adding an option to disable motion blur and chromatic aberration, if possible, of course ;). I am very sorry, that I used the Issues section for this.

**Comment by Lyall** [comment]
I've hooked up to the post process volumes to see what effects are enabled and here is a typical scene of gameplay.

![image](https://github.com/user-attachments/assets/42646bcb-ab67-4f03-907a-21731b2a2ece)

Does motion blur or chromatic aberration show up in cutscenes? 

Either way, I can add a toggle for motion blur, chromatic aberration and vignetting and they'll be disabled if they ever do show up.

**Comment by Lyall** [comment]
Added in v0.8.4.

**Comment by code-XmR** [comment]
I would like to apologize for such a long lack of response, the fix works flawlessly, your work is amazing. Thank you.
