### ISSUE TITLE
This product cannot be activated right now error.

### ISSUE THREAD

**Issue by sipso** [Lyall/PoPTLCFix#5]
![image](https://github.com/user-attachments/assets/a501e464-35ad-4d48-a346-020652458c4c)

Game installed on Ubisoft Connect. I "have" the Ubisoft+ version.

**Comment by Lyall** [comment]
I think you already got an answer to this on the WSGF Discord but I'll post this for posterity. You'll need a modified build of BepInEx for the Ubisoft+ version. 

At the moment the best way of getting that is to download the Ubisoft+ release of p1xel8ted's previous fix for the game from https://github.com/p1xel8ted/UltrawideFixes/releases/tag/PrinceOfPersiaTheLostCrown

**Comment by sipso** [comment]
Yes, this solution works. 

For anyone else who lands here put PoPTLCFix.dll from Lyall into p1xel8ted's \Prince of Persia The Lost Crown\BepInEx\plugins

The menus are 16:9 but the gameplay is ultrawide.

**Comment by Lyall** [comment]
Are you able to try [this build](https://github.com/Lyall/PoPTLCFix/releases/download/v0.8.6/PoPTLCFix_v0.8.6_UbisoftPlus.zip)? I've added p1xel8ted's changes to support Ubisoft+ versions to the latest BepInEx. If you can try that and let me know if it works, I can include it in subsequent release builds of PopTLCFix.

**Comment by sipso** [comment]
Yup, works fine. No tinkering needed.

![image](https://github.com/user-attachments/assets/81dcb37d-d2a4-40cb-8470-0a13bb800adc)

**Comment by Lyall** [comment]
Awesome, I've added the Ubisoft+ build to v0.8.6 onwards.
